OS := $(shell uname -s)

ifeq ($(OS), Darwin) 
  INCLUDE_PATH := /opt/homebrew/Cellar/criterion/2.4.1_1/include
  LIB_PATH := /opt/homebrew/Cellar/criterion/2.4.1_1/lib
  CC = gcc-12
endif
ifeq ($(OS), Linux) 
  INCLUDE_PATH := /util/criterion/include
  LIB_PATH := /util/criterion/lib/x86_64-linux-gnu
  CC = gcc
endif

CC = gcc -Wall 
INCLUDE_PATH := /util/criterion/include
LIB_PATH := /util/criterion/lib/x86_64-linux-gnu
DEBUG_Flags = -ggdb -O0 -c -Wall  
GCOV = -fprofile-arcs -ftest-coverage


code.o: code.c defs.h
	$(CC) -c $(DEBUG_FLAGS) $(GCOV) $(DEBUG_FLAGS) -pg code.c 

main.o: main.c defs.h
	$(CC) -c $(DEBUG_FLAGS) $(GCOV) $(DEBUG_FLAGS) -pg main.c 

tests.o: tests.c defs.h
	$(CC) -c $(DEBUG_FLAGS) $(GCOV) $(DEBUG_FLAGS) tests.c -lcriterion

main: main.o code.o defs.h
	$(CC) $(DEBUG_FLAGS) -L $(LIB_PATH) -I $(INCLUDE_PATH) $(GCOV) -pg -o main main.o code.o -lcriterion -lgcov

tests: tests.o code.o
	$(CC) $(DEBUG_FLAGS) -L $(LIB_PATH) -I $(INCLUDE_PATH) $(GCOV) -o tests tests.o code.o -lcriterion -lgcov

coverage: main tests
	./main 
	gcov -b code.c
	mv code.c.gcov main_coverage.txt
	./tests 
	gcov -b code.c
	mv code.c.gcov tests_coverage.txt

profile: main
	./main
	gprof -b ./main gmon.out> main_gprof.txt

memcheck: main tests
	valgrind --tool=memcheck --leak-check=yes --log-file=memcheckMain.txt ./main
	valgrind --tool=memcheck --leak-check=yes --log-file=memcheckTests.txt ./tests

callgrind: main tests
	valgrind --tool=callgrind ./main 1000 1000
	callgrind_annotate callgrind.out.* > main_callgrind.txt
	rm callgrind.out.*
	valgrind --tool=callgrind ./tests 1000 1000
	callgrind_annotate callgrind.out.* > tests_callgrind.txt

runTools: main tests
	make coverage
	make memcheck
	make callgrind
	make profile

	
.PHONY: clean
clean:
	rm -f *.o tests *.gcov *.gcda *.gcno sandbox-gmon* main *.out *.out.* main_* tests_* memcheck* callgrind*


info:
	@echo "User-targets:"
	@echo "\ttests - the executable for the Criterion tests"
	@echo "\tclean - remove Emacs autosave files and files generated by the compiler and gcov"
	@echo "\tinfo - print this message"
